Add ability to use multiple options

diff --git a/rav1ator-cli b/rav1ator-cli
--- a/rav1ator-cli
+++ b/rav1ator-cli
@@ -70,21 +70,76 @@ flag_version=0
 flag_offline=0
 flag_batch=0
 
-if [[ "$*" == "-h" || "$*" == "--help" ]]; then
-	flag_help=1
-elif [[ "$*" == "-l" || "$*" == "--last-used" ]]; then
-	flag_last_used=1
-elif [[ "$*" == "-f" || "$*" == "--full-history" ]]; then
-	flag_full_history=1
-elif [[ "$*" == "-b" || "$*" == "--binaries" ]]; then
-	flag_binaries=1
-elif [[ "$*" == "-v" || "$*" == "--version" ]]; then
-	flag_version=1
-elif [[ "$3" == "-x" || "$3" == "--offline" ]]; then
-	flag_offline=1
-elif [[ "$1" == "-a" || "$1" == "--batch" ]]; then
-	flag_batch=1
+getopt --test > /dev/null && true
+if [[ $? -ne 4 ]]; then
+    echo 'I’m sorry, `getopt --test` failed in this environment.'
+    exit 1
 fi
+
+LONGOPTS=help,last-used,full-history,binaries,version,offline,batch:
+OPTIONS=h,l,f,b,v,x,a:
+
+echo -e "${GREY}"
+PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@") || exit 2
+eval set -- "$PARSED"
+echo -e "${RESET}"
+
+while true; do
+	case "$1" in
+		-h|--help)
+			flag_help=0
+			flag_last_used=0
+			flag_full_history=0
+			flag_version=0
+			flag_help=1
+			shift
+			;;
+		-l|--last-used)
+			flag_help=0
+			flag_last_used=0
+			flag_full_history=0
+			flag_version=0
+			flag_last_used=1
+			shift
+			;;
+		-f|--full-history)
+			flag_help=0
+			flag_last_used=0
+			flag_full_history=0
+			flag_version=0
+			flag_full_history=1
+			shift
+			;;
+		-b|--binaries)
+			flag_binaries=1
+			shift
+			;;
+		-v|--version)
+			flag_help=0
+			flag_last_used=0
+			flag_full_history=0
+			flag_version=0
+			flag_version=1
+			shift
+			;;
+		-x|--offline)
+			flag_offline=1
+			shift
+			;;
+		-a|--batch)
+			flag_batch="$2"
+			shift 2
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo -e "${GREY}Unexpected Error${RESET}"
+			exit 3
+			;;
+	esac
+done
 
 # If the user passes a help flag
 if [[ $flag_help -ne 0 ]]; then
@@ -260,14 +315,9 @@ fi
 if [[ $flag_offline -ne 0 ]]; then
 	script_md5="DEBUG"
 fi
-if [[ flag_batch -ne 0 ]]; then
-	if [ -z "$2" ]; then
-		echo -e "${GREY}No directory string provided.${RESET}"
-		exit 1
-	fi
+if [[ "$flag_batch" != "0" ]]; then
 	is_batch_encode=1
-	batch_dir_dumb="$2"
-	batch_dir=$(echo "$batch_dir_dumb" | tr -d '/')
+	batch_dir=$(echo "$flag_batch" | tr -d '/')
 fi
 
 # If the user has different args or no args, print generic output
